CC = gcc-3.2
LDFLAGS =
CFLAGS =
CPPFLAGS =
MAKE = make

all: buckets2 classes classes1 client_s conf do_strea evnt_ar1 evnt_arr ex1 ex1_stre ex2 gensys hist moving_a moving_q msgs my_main my_main1 pre_res process_ qhist register rerun rerun1 reset rnd_pri rnd_rob setjmp storages syn_fac syn_stor timed_re timed_wa

../lib/csim.a:
	(cd ../lib && $(MAKE))

buckets2: buckets2.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o buckets2 buckets2.c ../lib/csim.a -lm

classes: classes.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o classes classes.c ../lib/csim.a -lm

classes1: classes1.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o classes1 classes1.c ../lib/csim.a -lm

client_s: client_s.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o client_s client_s.c ../lib/csim.a -lm

conf: conf.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o conf conf.c ../lib/csim.a -lm

do_strea: do_strea.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o do_strea do_strea.c ../lib/csim.a -lm

evnt_ar1: evnt_ar1.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o evnt_ar1 evnt_ar1.c ../lib/csim.a -lm

evnt_arr: evnt_arr.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o evnt_arr evnt_arr.c ../lib/csim.a -lm

ex1: ex1.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o ex1 ex1.c ../lib/csim.a -lm

ex1_stre: ex1_stre.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o ex1_stre ex1_stre.c ../lib/csim.a -lm

ex2: ex2.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o ex2 ex2.c ../lib/csim.a -lm

gensys: gensys.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o gensys gensys.c ../lib/csim.a -lm

hist: hist.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o hist hist.c ../lib/csim.a -lm

moving_a: moving_a.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o moving_a moving_a.c ../lib/csim.a -lm

moving_q: moving_q.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o moving_q moving_q.c ../lib/csim.a -lm

msgs: msgs.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o msgs msgs.c ../lib/csim.a -lm

my_main: my_main.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o my_main my_main.c ../lib/csim.a -lm

my_main1: my_main1.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o my_main1 my_main1.c ../lib/csim.a -lm

pre_res: pre_res.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o pre_res pre_res.c ../lib/csim.a -lm

process_: process_.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o process_ process_.c ../lib/csim.a -lm

qhist: qhist.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o qhist qhist.c ../lib/csim.a -lm

register: register.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o register register.c ../lib/csim.a -lm

rerun: rerun.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o rerun rerun.c ../lib/csim.a -lm

rerun1: rerun1.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o rerun1 rerun1.c ../lib/csim.a -lm

reset: reset.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o reset reset.c ../lib/csim.a -lm

rnd_pri: rnd_pri.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o rnd_pri rnd_pri.c ../lib/csim.a -lm

rnd_rob: rnd_rob.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o rnd_rob rnd_rob.c ../lib/csim.a -lm

setjmp: setjmp.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o setjmp setjmp.c ../lib/csim.a -lm

storages: storages.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o storages storages.c ../lib/csim.a -lm

syn_fac: syn_fac.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o syn_fac syn_fac.c ../lib/csim.a -lm

syn_stor: syn_stor.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o syn_stor syn_stor.c ../lib/csim.a -lm

timed_re: timed_re.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o timed_re timed_re.c ../lib/csim.a -lm

timed_wa: timed_wa.c ../lib/csim.a
	$(CC) -I../lib $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) -o timed_wa timed_wa.c ../lib/csim.a -lm

clean:
	rm -f buckets2 classes classes1 client_s conf do_strea evnt_ar1 evnt_arr ex1 ex1_stre ex2 gensys hist moving_a moving_q msgs my_main my_main1 pre_res process_ qhist register rerun rerun1 reset rnd_pri rnd_rob setjmp storages syn_fac syn_stor timed_re timed_wa
